services:
  videobench.web:
    image: videobench.web
    container_name: videobench.api
    build:
      context: .
      dockerfile: src/VideoBench.Web/Dockerfile
    ports:
      - "5000:8080"

  videobench.keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: videobench.keycloak
    command: start-dev
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - keycloak:/opt/keycloak/data/
    ports:
      - "127.0.0.1:18080:8080"

volumes:
  keycloak:
