services:
  videobench.backend:
    image: videobench.backend
    container_name: videobench.backend
    build:
      context: .
      dockerfile: src/VideoBench.Web/Dockerfile
    ports:
      - '5000:8080'
    expose:
      - '5000'

  videobench.frontend:
    image: videobench.frontend
    container_name: videobench.app
    build:
      context: ./src/VideoBench.Web/ClientApp
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    expose:
      - '3000'

  videobench.keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: videobench.keycloak
    command: start-dev
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - keycloak:/opt/keycloak/data/
    ports:
      - '18080:8080'
    expose:
      - '18080'

  videobench.database:
    image: postgres:latest
    container_name: videobench.database
    environment:
      - POSTGRES_DB=tests
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - '5432'

  videobench.minio:
    image: quay.io/minio/minio:latest
    container_name: videobench.minio
    command: server --console-address ":9001" /data
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio:/data

volumes:
  keycloak:
  pgdata:
  minio:
