services:
  videobench.backend:
    image: videobench.backend
    container_name: videobench.backend
    build:
      context: .
      dockerfile: src/VideoBench.Web/Dockerfile
    ports:
      - "127.0.0.1:5000:8080"

  videobench.frontend:
    image: videobench.frontend
    container_name: videobench.app
    build:
      context: ./src/VideoBench.Web/ClientApp
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:3000:3000"

  videobench.keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: videobench.keycloak
    command: start-dev
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - keycloak:/opt/keycloak/data/
    ports:
      - "127.0.0.1:18080:8080"

volumes:
  keycloak:
